### ISSUE TITLE
download link not working

### ISSUE THREAD

**Issue by sudip550** [jinix6/terabox-downloader#2]
getting this error = {
  "error_code": 31071,
  "error_msg": "get file meta failed , failed get file meta"
}

**Comment by jinix6** [comment]
Check updated Site: [Updated Site](https://jinix6.github.io/terabox-downloader)

**Comment by sudip550** [comment]
can you please share source code?

**Comment by sudip550** [comment]
> Check updated Site: [Updated Site](https://jinix6.github.io/terabox-downloader)

can you please share source code?
